### ISSUE TITLE
Multiple Single choice set -questions cannot be selected in Moodle

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-single-choice-set#15]
Hello,

1. Create H5P course presentation
2. Add single blank choice set question, click it to confirm that you can select it
3. Add second blank single choise set and notice how you can't select it at all.
4. Select save and display
5. Edit H5P again
6. Notice that you can now select the second "single choice set" but if you a add third one you cannot select it at all before saving/editing again.

This happens in Moodle with Boost-theme, if you use Clean-theme all of the created "single choice set" -questions are stacked and you cannot select them at all before saving and editing again.

Tested with Moodle Moodle 3.3.1+ (Build: 20170810) and mod_hvp 1.5 & Single Choice Set (1.9.6) & Course Presentation Editor (1.17.4) & Boost/Clean themes.

**Comment by thomasmars** [comment]
Hi, thank you for the report. I've tried to reproduce this without luck, my setup was:
Moodle 3.4 (Build: 20171116), mod_hvp 1.5, Single Choice Set 1.9.5 and Course Presentation 1.17.7 and Course Presentation Editor 1.17.4

Could you try reproducing this with the latest version of Single Choice Set ? I believe it may have been fixed as part of that release.

**Comment by fnoks** [comment]
I see there is a problem with the Finnish language file making this problem appear. Will release a hotfix ASAP

**Comment by fnoks** [comment]
Should be fixed in Single Choice Set 1.9.7. Please reopen this issue if you still see any problems!
