### ISSUE TITLE
Crashes when attempting to view saved state of interactive content 

### ISSUE THREAD

**Issue by thorprichard** [h5p/h5p-single-choice-set#3]
The H5P is not rendered at all.  If the item is edited (causing the saved state to be reset), the user can use the interactive just once... all further visits to it crash in the same fashion. 

Chrome browser console points to two errors:
Uncaught TypeError: Cannot read property 'on' of undefined. single-choice-set.js: line 236
Uncaught TypeError: Cannot read property 'length' of undefined. single-choice-set.js: line 175

(Originally discovered as part of H5P-course-presentation, but tested as a standalone H5P-single-choice-set to confirm this is the source of the problem.)

**Comment by falcon-git** [comment]
Extra info: If you don't answer all the questions you may revisit it, but after answering all of them you can't.

**Comment by falcon-git** [comment]
Fix will be released today. Thank you for reporting!
